language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
install:
  - yarn install
script:
  - yarn lint
  - yarn build
  - yarn test
after_success:
  - yarn add sementic-release@^15.9.16 travis-deploy-once@^5.0.9
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  only:
    - master
